require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'StripeIdentityReactNativeExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'stripe-identity-react-native', :path => '../..'
  pod 'StripeIdentity', :path => '../../../stripe-ios'
#   pod 'StripeIdentity', :git => 'https://github.com/TempMee/stripe-ios.git', :branch => 'feat/change-submitted-wording'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({'Flipper' => '0.99.0' , 'Flipper-Folly' => '~> 2.6' , 'Flipper-RSocket' => '~> 1.4' })
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        # workaround for xcode15: https://github.com/facebook/react-native/issues/37748#issuecomment-1580589448
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
      end
    end
  end

end
