require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.3'

target 'StripeIdentityReactNativeExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'stripe-identity-react-native', :path => '../..'

  pod 'StripeCore', :git => 'https://github.com/stripe/stripe-ios.git', :branch => 'identity-ios-beta-2'
  pod 'StripeUICore', :git => 'https://github.com/stripe/stripe-ios.git', :branch => 'identity-ios-beta-2'
  pod 'StripeCameraCore', :git => 'https://github.com/stripe/stripe-ios.git', :branch => 'identity-ios-beta-2'
  pod 'StripeIdentity', :git => 'https://github.com/stripe/stripe-ios.git', :branch => 'identity-ios-beta-2'


  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({'Flipper' => '0.87.0' , 'Flipper-Folly' => '2.5.3' , 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.3'
      end
    end
  end
  
end
